spring.application.name=api-gateway
# Server
server.port=8080

# Spring Cloud Gateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# JWT
jwt.secret=SuperSecretSigningKeyForEcommercePlatform3YearExpSecretKey

# Logging
logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.ecommerce.gateway=DEBUG